name:

on:
  pull_request:
    branches:
      - master

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: before_install
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get -y install docker-ce
          docker --version
          sudo docker pull ${distribution}:${version}
          sudo docker build --no-cache --rm --file=Dockerfile --tag=angular-meteor:latest .
      - name: install
        run: |
          sudo docker run -td --memory 2304m --volume ${TRAVIS_BUILD_DIR}:/angular-meteor-sourcecode/ --name=angular-meteor-container angular-meteor:latest
          sudo docker exec --user docker --workdir /angular-meteor-sourcecode angular-meteor-container bash -c 'source $HOME/.nvm/nvm.sh; git clean -fXd; npm cache verify; npm install -g concurrently'
      - name: before_script
        run: |
          sudo docker exec --user root --workdir /angular-meteor-sourcecode angular-meteor-container bash -c 'chown -R docker /angular-meteor-sourcecode'
      - name: script
        run: |
          sudo docker stats --no-stream
          sudo free -m"
          sudo docker exec --user docker --workdir /angular-meteor-sourcecode angular-meteor-container bash -c 'source $HOME/.nvm/nvm.sh; export QT_QPA_PLATFORM=offscreen; /angular-meteor-sourcecode/run_tests.sh