name:

on:
  pull_request:
    branches:
      - master

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Use Meteor
        uses: actions/setup-node@v2
        with:
          meteor-release: '2.0.0'
      - name: Run Tests
        run: ./run_tests.sh
